import Link from "next/link";import GalleryCarousel from"./GalleryCarousel";import{auraPortraits}from"./galleryData";import{Header}from"./shared";
const services=[
 {id:"aura",href:"/aura-photography",title:"Aura Photography",copy:"See the colors, patterns, chakra levels, and energetic data reflected through biofeedback technology—then explore what the results may mean for you.",detail:"15–30 minutes · from $50",image:"/images/gallery/aura-red-poodle.jpg"},
 {id:"reiki",href:"/reiki",title:"Reiki Sessions",copy:"A calming, client-centered energy practice offered in person or remotely to support relaxation, reflection, and a renewed sense of balance.",detail:"30–90 minutes · from $60",image:"/images/gallery/reiki-demonstration.jpg"},
 {id:"hypnosis",href:"/hypnosis",title:"Hypnosis",copy:"Work with the conscious and subconscious mind in a focused, supportive setting designed around the change you want to create.",detail:"Private sessions · consultation first",image:"/images/gallery/shana-speaking.jpg"},
 {id:"clearing",href:"/energy-clearing",title:"Energy Clearing",copy:"Respectful, intuitive clearing sessions for people, homes, land, offices, and businesses experiencing heavy or unexplained energy.",detail:"Portland area · rates by request",image:"/images/gallery/investigation-attic.jpg"}
];
const posts=[
 ["Understanding Auras","What does an aura camera actually measure?","A grounded look at biofeedback, color interpretation, and what to expect from your first aura portrait."],
 ["Reiki & Energy Work","What a Reiki session feels like","How the experience unfolds—and how to arrive without needing to believe anything first."],
 ["Hypnosis","You are not asleep and nobody controls you","Separating stage-show mythology from the focused, collaborative state used in a private session."]
];
export default function Home(){return <main id="top" className="tone-violet">
 <Header home/>
 <section className="hero videoHero"><video className="heroVideo" autoPlay muted loop playsInline preload="metadata" poster="/images/story/shana-walking-into-sunset.jpg" aria-hidden="true"><source src="/video/aura-moon-hero.mp4" type="video/mp4"/></video><div className="heroShade"/><div className="heroCopy"><h1>There is more to you than meets the eye.</h1><p className="lead">Aura photography, Reiki, hypnosis, and energy clearing with Shana Madsen—helping people explore what they feel, what they carry, and what they are ready to change.</p></div><div className="heroSignature"><strong>Shana Madsen</strong><span>Reiki Master Teacher · Certified Hypnotist<br/>Aura Photographer & Analyst</span></div></section>
 <section className="mantra"><p>Technology can show us a pattern.</p><p>Experience helps us understand it.</p><p>Intuition helps us ask what comes next.</p></section>
 <section className="mediaProof" aria-label="Featured media and appearances"><p className="eyebrow">Featured, filmed & heard</p><a href="https://www.columbian.com/news/2026/aug/05/aura-imagery-offers-look-at-ones-energy/" target="_blank" rel="noreferrer">The Columbian</a><a href="https://www.king5.com/article/entertainment/television/programs/evening/ghosts-touch-humans-naked-seattle-ghosthunter/281-9bf79e90-55a6-4505-b675-f491df8ef2ff" target="_blank" rel="noreferrer">KING 5</a><a href="https://www.imdb.com/name/nm13735845/" target="_blank" rel="noreferrer">IMDb</a><a href="https://tubitv.com/movies/100000812/parasense-the-naked-experiments" target="_blank" rel="noreferrer">Tubi</a><Link href="/media">View all media →</Link></section>
 <GalleryCarousel compact eyebrow="Real Aura About You portraits" title="No two people show up the same" images={auraPortraits}/>
 <section className="section" id="services"><div className="heading"><p className="eyebrow">Ways to work with Shana</p><h2>Begin with curiosity.</h2><p>You do not need a perfect question or a fixed belief. You only need a willingness to notice what is present.</p></div><div className="services">{services.map(s=><article id={s.id} key={s.title}><img src={s.image} alt="" loading="lazy"/><div><h3>{s.title}</h3><p>{s.copy}</p><footer><span>{s.detail}</span><Link href={s.href}>Explore service →</Link></footer></div></article>)}</div></section>
 <section className="section authorityAbout" id="about"><div className="authorityPhoto"><img src="/images/gallery/shana-oregon.jpg" alt="Shana Madsen outdoors in the Oregon mountains"/><p>Healing arts practitioner · educator · paranormal researcher</p></div><div className="aboutCopy"><p className="eyebrow">Meet your practitioner</p><h2>Shana Madsen</h2><p className="large">An uncommon path through healing, death and transition, consciousness, and the unexplained.</p><p>A former Multnomah County Medical Examiner&apos;s Office staff member, Shana is a Usui Holy Fire Reiki Master Teacher, Certified Hypnotist, Shamanic Practitioner, INELDA-trained End-of-Life Doula, Energy Medicine Practitioner, and Aura Photographer and Analyst.</p><div className="credentialGrid"><span>15+ years<br/><b>Healing arts</b></span><span>Since 2016<br/><b>Aura imagery</b></span><span>Film & media<br/><b>ParaSense · KING 5</b></span><span>Teacher<br/><b>Reiki · energy work</b></span></div><div className="aboutLinks"><Link className="btn" href="/about">Meet Shana</Link><Link className="line" href="/journal/from-medical-examiner-office-to-paranormal-research">Read her unusual path →</Link></div></div></section>
 <section className="quote"><b>“</b><blockquote>I am prone to be a skeptic, so I didn&apos;t know what to expect. Shana helped me understand the data. Using my scan, I was able to confront repressed emotions. The results have been both immediate and continuous.</blockquote><cite>Mark H. · Aura photography client</cite></section>
 <section className="section events"><div><p className="eyebrow">Private events & gatherings</p><h2>Give your guests something they will actually remember.</h2></div><div><p>Aura portraits create natural conversation, curiosity, and connection at corporate events, birthdays, reunions, retreats, conferences, and team-building gatherings.</p><ul><li>Individual aura portraits and reports</li><li>Interpretation by an experienced practitioner</li><li>Group rates and travel options available</li></ul><Link className="btn light" href="/private-events">Explore private events</Link></div></section>
 <section className="section journal" id="journal"><div className="heading"><p className="eyebrow">Notes from the field</p><h2>The Aura Journal</h2><p>Clear answers for curious people—without requiring you to speak fluent metaphysics.</p></div><div className="posts">{posts.map((p,i)=><article key={p[1]}><small>{p[0]}</small><h3>{p[1]}</h3><p>{p[2]}</p><Link href={["/journal/what-aura-camera-measures","/journal/what-reiki-feels-like","/journal/hypnosis-myths"][i]}>Read article →</Link></article>)}</div></section>
 <section className="contact" id="contact"><div><p className="eyebrow">Portland · Remote sessions available</p><h2>What are you curious about?</h2><p>Ask a question, choose a session, or invite Shana to your next event.</p></div><div><Link className="btn" href="/book">Choose your session</Link><a className="line" href="mailto:talkwithshana@gmail.com">Ask Shana a question →</a><a className="line" href="tel:+15033101135">503-310-1135 →</a><p>The Haven at JaJa PDX<br/>819 SE Taylor Street<br/>Portland, Oregon 97214</p></div></section>
 <footer className="siteFooter"><a className="brand" href="#top"><b>A</b><span>Aura About You</span></a><p>Exploration, insight, and energetic care with Shana Madsen.</p><div><a href="https://www.facebook.com/talkwithshana/">Facebook</a> · <a href="https://www.instagram.com/knottyshaman/">Instagram</a></div><p className="legal">Services are intended for personal exploration and relaxation and do not replace medical or mental-health care.</p></footer>
 </main>}
