import Link from "next/link";import GalleryCarousel from"./GalleryCarousel";import MobileMenu from"./MobileMenu";import type{GalleryImage}from"./galleryData";
export const bookingHref="mailto:talkwithshana@gmail.com?subject=Session%20inquiry";
const navItems=[["Services","/#services"],["About Shana","/about"],["Media","/media"],["Gallery","/gallery"],["Journal","/journal"],["Contact","/#contact"]];
export function Header({home=false}:{home?:boolean}){const link=(href:string)=>home?href.replace("/",""):href;return <header><Link className="brand" href={home?"#top":"/"}><b>A</b><span>Aura About You</span></Link><nav>{navItems.map(([label,href])=><Link key={label} href={link(href)}>{label}</Link>)}</nav><MobileMenu/><a className="btn small headerBook" href={home?"#contact":bookingHref}>Book a session</a></header>}
export function Footer(){return <footer className="siteFooter"><Link className="brand" href="/"><b>A</b><span>Aura About You</span></Link><p>Exploration, insight, and energetic care with Shana Madsen.</p><div><a href="https://www.facebook.com/talkwithshana/">Facebook</a> · <a href="https://www.instagram.com/knottyshaman/">Instagram</a></div><p className="legal">Services are intended for personal exploration and relaxation and do not replace medical or mental-health care.</p></footer>}
type AuraTone="violet"|"indigo"|"blue"|"green"|"red"|"orange"|"yellow";
type ServiceProps={tone:AuraTone;eyebrow:string;title:string;intro:string;image:string;imageAlt:string;facts:string[];children:React.ReactNode;faq:{q:string;a:string}[];cta:string;gallery?:GalleryImage[];galleryTitle?:string};
export function ServiceDetail({tone,eyebrow,title,intro,image,imageAlt,facts,children,faq,cta,gallery,galleryTitle="From the field"}:ServiceProps){return <main className={`tone-${tone}`}><Header/><section className="detailHero"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lead">{intro}</p><a className="btn" href={bookingHref}>{cta}</a></div><img src={image} alt={imageAlt}/></section><section className="factBar">{facts.map(f=><span key={f}>{f}</span>)}</section>{gallery&&<GalleryCarousel compact eyebrow="Real moments" title={galleryTitle} images={gallery}/>}<section className="articleShell"><article className="prose">{children}</article><aside><p className="eyebrow">Ready when you are</p><h3>Begin with a conversation.</h3><p>Tell Shana what brought you here, ask anything you need, and choose the experience that feels right.</p><a className="btn" href={bookingHref}>Contact Shana</a><a className="line" href="tel:+15033101135">503-310-1135 →</a></aside></section><section className="faq"><p className="eyebrow">Common questions</p><h2>Before your session</h2><div>{faq.map(x=><details key={x.q}><summary>{x.q}<span>+</span></summary><p>{x.a}</p></details>)}</div></section><section className="nextStep"><p className="eyebrow">Aura About You · Portland, Oregon</p><h2>{cta}</h2><a className="btn light" href={bookingHref}>Email Shana</a></section><Footer/></main>}
type ArticleProps={tone:AuraTone;category:string;title:string;dek:string;children:React.ReactNode;author?:string};
export function JournalArticle({tone,category,title,dek,children,author="Shana Madsen"}:ArticleProps){return <main className={`tone-${tone}`}><Header/><article className="journalArticle"><div className="articleHead"><p className="eyebrow">{category}</p><h1>{title}</h1><p className="lead">{dek}</p><span>August 2026 · By {author}</span></div><div className="prose articleBody">{children}</div><div className="articleCta"><p className="eyebrow">Explore it for yourself</p><h2>Some things make more sense when you experience them.</h2><a className="btn" href={bookingHref}>Ask Shana about a session</a></div></article><Footer/></main>}
