import type{Metadata}from"next";
import{JournalArticle}from"../../shared";

export const metadata:Metadata={title:"From the Medical Examiner’s Office to Paranormal Research | Shana Madsen",description:"How Shana Madsen’s unusual path through death and transition, Reiki, hypnosis, shamanic practice, aura imagery, and paranormal research shaped Aura About You."};

export default function Page(){return <JournalArticle tone="violet" category="Shana’s Story" author="Aura About You" title="From the Medical Examiner’s Office to paranormal research" dek="Shana Madsen’s work did not emerge from one tidy discipline. It grew where death, transition, consciousness, healing, technology, and the unexplained overlap.">
 <p className="drop">Some professional lives make sense as a straight line. Shana Madsen&apos;s makes more sense as a constellation: experiences that appeared separate at first, but gradually revealed a common center.</p>
 <p>Before Aura About You became the public expression of her work, Shana served on the staff of the Multnomah County Medical Examiner&apos;s Office under her former name, Shana P. Aivaliotis. Public county employment records place her within the Health Department from 2014 through 2017 with the payroll title Senior Office Assistant. That title matters because accuracy matters: she was not the medical examiner. She was, however, working inside an institution shaped by death, evidence, grief, unanswered questions, and the lives affected after someone dies.</p>
 <h2>Death and transition were never abstract subjects</h2>
 <p>For many people, death remains distant until it arrives personally. Work connected to a Medical Examiner&apos;s Office removes some of that distance. It puts mortality, bereavement, official process, and the questions left behind into the landscape of ordinary life.</p>
 <p>That chapter does not “prove” anything paranormal, nor does it function as a healing credential. Its importance is human. It helps explain why Shana&apos;s later work with psychopomp traditions, end-of-life support, energy practice, and paranormal inquiry is not built around spectacle. She understands that conversations about death belong to real people.</p>
 <h2>Learning to work with mind, energy, and meaning</h2>
 <p>Over more than fifteen years in the Healing Arts, Shana pursued several disciplines rather than forcing every human experience through one method. She became a Certified Hypnotist after professional training through Northwest Hypnosis Institute. She trained through the first two core levels of LightSong School of 21st Century Shamanism and Energy Medicine. She completed End-of-Life Doula Training through the International End-of-Life Doula Association.</p>
 <p>She also became a Usui Holy Fire Reiki Master Teacher—moving beyond receiving or practicing Reiki into teaching, attunement, and supporting other practitioners. Her public work has included Reiki circles, certification programs, energy-healing classes, meditation and attunement, private sessions, and conference instruction.</p>
 <p>Each discipline brings a different lens. Hypnosis attends to focused attention and subconscious patterns. Reiki offers a structured energy practice centered on relaxation, intention, and care. Shamanic training engages journey, relationship, ritual, and transition. End-of-life doula training emphasizes presence, autonomy, listening, and support around dying and grief.</p>
 <h2>Giving an invisible conversation a visual language</h2>
 <p>In 2016, Shana added aura-imagery technology to her practice. The system begins with physical inputs from a hand sensor, including electrodermal activity and skin temperature. Software then translates those inputs into symbolic colors, charts, chakra information, and visual simulations.</p>
 <p>Shana does not need the technology to settle every metaphysical question. Its value is that it gives people something visible to explore. Measurement, software interpretation, practitioner experience, and the client&apos;s own understanding remain distinct parts of the conversation.</p>
 <p>Since introducing the technology, she has brought aura imagery to private sessions, metaphysical gatherings, festivals, conferences, retreats, paranormal investigations, and events from coast to coast.</p>
 <h2>The paranormal became fieldwork</h2>
 <p>Shana&apos;s lifelong interest in paranormal phenomena eventually moved into public investigation, education, media, and film. She taught Psychopomping 101 at the Oregon Ghost Conference in 2018 and returned to its official 2026 program with Reiki Meditation &amp; Attunement. She has discussed auras, thinning the veil, energy, attachments, clearing, Reiki, shamanism, and paranormal experience through podcasts and interviews.</p>
 <p>She also appears in the cast of <em>ParaSense: The Naked Experiments</em>, a multi-award-winning documentary following an unusual paranormal experiment. The film&apos;s recognition belongs to the production as a whole; Shana&apos;s place in it is as a participating cast member bringing her own sensitivity, experience, and perspective to the work.</p>
 <h2>A practice built at the intersections</h2>
 <p>Aura About You is not the result of one weekend certificate or a sudden spiritual rebrand. It is the current expression of a long, unusual path: institutional contact with death and aftermath; formal training in hypnosis, Reiki, shamanic practice, and end-of-life support; years of client work; aura-imagery technology; teaching; investigation; and public conversation.</p>
 <p>The through-line is not certainty. It is Shana&apos;s willingness to remain present where people encounter mystery—inside themselves, around death and transition, in the patterns recorded by a sensor, or in experiences that resist easy explanation.</p>
 <div className="articleSources"><h2>Explore the record</h2><p><a href="/media">Media, film, podcasts, and conference appearances →</a></p><p><a href="https://www.portlandhypnosistraining.org/" target="_blank" rel="noreferrer">Northwest Hypnosis Institute ↗</a></p><p><a href="https://www.lightsong.net/all-lightsong-shamanic-courses/core-courses/" target="_blank" rel="noreferrer">LightSong core training ↗</a></p><p><a href="https://inelda.org/learn/end-of-life-doula-training/" target="_blank" rel="noreferrer">INELDA End-of-Life Doula Training ↗</a></p></div>
 </JournalArticle>}
