import type{Metadata}from"next";
import{Footer,Header}from"../shared";

export const metadata:Metadata={title:"Media, Film & Appearances | Shana Madsen",description:"Explore press, television, film, podcasts, and conference appearances featuring Aura About You founder Shana Madsen."};

const appearances=[
 {type:"Press feature",year:"2026",title:"Aura imagery offers look at one’s energy",source:"The Columbian",copy:"Reporter Kimberly Cortez visits Shana for an aura-imagery session and explores the technology, interpretation, and experience behind an Aura About You reading.",href:"https://www.columbian.com/news/2026/aug/05/aura-imagery-offers-look-at-ones-energy/",cta:"Read the feature"},
 {type:"Television",year:"2022",title:"Ghosts touch humans in ‘naked’ Seattle experiment",source:"KING 5 Evening",copy:"An Evening television feature on the paranormal experiment and documentary that became ParaSense: The Naked Experiments.",href:"https://www.king5.com/article/entertainment/television/programs/evening/ghosts-touch-humans-naked-seattle-ghosthunter/281-9bf79e90-55a6-4505-b675-f491df8ef2ff",cta:"Watch the story"},
 {type:"Podcast",year:"2025",title:"Oregon Ghost Conference 2025 — Episode 785",source:"Into the Parabnormal",copy:"A conference conversation featuring Shana on thinning the veil and the territory where energy work, transition, and paranormal experience meet.",href:"https://poddtoppen.se/podcast/1483377360/into-the-parabnormal/ep-785-oregon-ghost-conference-2025",cta:"Hear the episode"},
 {type:"Podcast",year:"2025",title:"Segment 258: Shana Madsen",source:"Paranormal Encounters",copy:"Shana joins Dr. Kelly Schutz to discuss Reiki, hypnosis, aura photography, energy, and paranormal encounters.",href:"https://www.podomatic.com/podcasts/krschutz1paranormalencounters/episodes/2025-04-17T21_41_28-07_00",cta:"Hear the episode"},
 {type:"Conference",year:"2026",title:"Reiki Meditation & Attunement",source:"Oregon Ghost Conference",copy:"A two-hour class led by Shana as part of the official Oregon Ghost Conference program.",href:"https://www.oregonghostconference.com/Schedule.html",cta:"View the schedule"},
 {type:"Conference class",year:"2018",title:"Psychopomping 101",source:"Oregon Ghost Conference",copy:"Shana’s two-hour introduction to psychopomp work, death, transition, and helping spirits move onward.",href:"https://www.facebook.com/oregonghostconference/posts/our-fifth-class-offered-sunday-march-25th-12-2-pm-is-psychopomping-101-2hr-20-wi/2018648508164095/",cta:"View the announcement"}
];

export default function MediaPage(){return <main className="tone-yellow"><Header/>
 <section className="mediaHero"><p className="eyebrow">Media · Film · Podcasts · Conferences</p><h1>A life spent exploring what most people overlook.</h1><p className="lead">Shana Madsen’s work has carried her from healing rooms and aura-imagery events to paranormal investigations, conference classrooms, podcasts, television, and documentary film.</p></section>
 <section className="filmFeature"><div><p className="eyebrow">Featured film</p><h2>ParaSense:<br/>The Naked Experiments</h2><p>Shana appears in the cast of the multi-award-winning 2022 documentary following a group of psychics, sensitives, and paranormal investigators through an unusual controlled experiment.</p><div className="filmActions"><a className="btn light" href="https://tubitv.com/movies/100000812/parasense-the-naked-experiments" target="_blank" rel="noreferrer">Watch free on Tubi</a><a className="line" href="https://www.imdb.com/name/nm13735845/" target="_blank" rel="noreferrer">Shana on IMDb →</a></div></div><div className="awardPanel"><span>2022</span><strong>Festival-recognized documentary</strong><p>The published winners lists document at least ten Platinum Fortean Film Festival honors and at least four MegaFlix Film Awards for the film.</p><a href="https://irp.cdn-website.com/f7ee72db/files/uploaded/FFF22WIN.pdf" target="_blank" rel="noreferrer">Fortean winners ↗</a><a href="https://irp.cdn-website.com/f7ee72db/files/uploaded/MFA22WIN.pdf" target="_blank" rel="noreferrer">MegaFlix winners ↗</a></div></section>
 <section className="appearanceSection"><div className="heading"><p className="eyebrow">Selected appearances</p><h2>In print, on screen, and behind the microphone.</h2><p>Each item links to the original public source.</p></div><div className="appearanceGrid">{appearances.map(x=><article key={x.title}><div><small>{x.type} · {x.year}</small></div><p className="appearanceSource">{x.source}</p><h3>{x.title}</h3><p>{x.copy}</p><a href={x.href} target="_blank" rel="noreferrer">{x.cta} →</a></article>)}</div></section>
 <section className="mediaStatement"><p className="eyebrow">Available for thoughtful conversations</p><h2>Auras, Reiki, hypnosis, energy medicine, death and transition, and paranormal research.</h2><a className="btn" href="mailto:talkwithshana@gmail.com?subject=Media%20or%20speaking%20inquiry">Invite Shana to speak</a></section>
 <Footer/></main>}
